---

- name: configure sshd
  hosts: salt
  remote_user: root
  gather_facts: no

  tasks:
  - name: configure sshd
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "^(#|){{item.key}}"
      line: "{{item.key}} {{item.value}}"
      state: present
    loop:
      - { key: "PermitRootLogin", value: "yes" }
      - { key: "PasswordAuthentication", value: "no" }
      - { key: "AuthorizedKeysFile", value: "/etc/ssh_keys/%u"}
    notify:
      - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
